### ISSUE TITLE
Error during computing moon phase

### ISSUE THREAD

**Issue by lmillett** [davideilmito/MoonKit#1]
I found yesterday at 12:27 pm PST at location latitude: 47.588889, longitude: -122.527778 that the package was unable to correctly calculate the new moon phase. The variable ageOfTheMoonInDays is being calculated as -0.06587243342914535 and ageOfTheMoonInDegrees as -0.8030310742046822 so the switch statement was falling through to the error case. Unfortunately I don't understand the math well enough to take a stab at fixing it. Hopefully the provided information is enough to duplicate the state.

**Comment by davideilmito** [comment]
Hi lmillet, could you please specific the date and the timezone used? Thanks!

**Comment by lmillett** [comment]
Yes. The date was January 21, 2023 at 12:27 pm Pacific standard time with a UTC offset of -8.

**Comment by davideilmito** [comment]
Fix is on main branch. Thanks for the support lmillet! 
If you liked the package leave a star :)

**Comment by lmillett** [comment]
I verified the fix in my app. Thanks for the quick turnaround! Added a star as well. Will you be updating the package?
