### ISSUE TITLE
Failing Test Assertions

### ISSUE THREAD

**Issue by nickkohrn** [davideilmito/MoonKit#19]
Currently, seven test assertions are failing.

![CleanShot 2024-01-01 at 22 38 57@2x](https://github.com/Sunlitt/MoonKit/assets/5864877/195619ab-701a-440d-aa80-81b6af49881f)

**Comment by davideilmito** [comment]
@nickkohrn are you on main branch?

This is what I get when I run all UT test suite.

![image](https://github.com/Sunlitt/MoonKit/assets/81416309/abfa7f88-bddd-4fe4-8f28-d44277103286)

**Comment by davideilmito** [comment]
Not able to reproduce.
