### ISSUE TITLE
AstrologicalSign: Using the moon's ecliptic longitude?

### ISSUE THREAD

**Issue by hannsadrian** [davideilmito/MoonKit#20]
Hey, I just stumbled over your library and found it fitting for my current side project!

On thing though: The implementation of astronomical signs is imho wrong. Instead of the ecliptic longitude of the sun, you're using the one of the moon (see https://en.wikipedia.org/wiki/Astrological_sign)

Do you think this can easily be fixed?

**Comment by davideilmito** [comment]
Hi, what the package is giving is the moon astrological sign, not the sun one. So it's correct.
