### ISSUE TITLE
How to calculate the value for setTimeZone()?

### ISSUE THREAD

**Issue by BlackBird-One** [davideilmito/MoonKit#7]
I don't think it is possible to write a function to calculate the value to be set in setTimeZone(). 

I have prepared unit testing that demonstrates the problem. 

The calculation is attempted by the TimeZone.offset(date) function, which only works sometimes. I don't think the correct value can be calculated. 

The control data is from www.timeanddate.com 

The current time zone of the application is "CET" (Prague), calculated for Cupertino, time zone "PST".

(Sorry for the confusion. I wrote down the error once before, but since I thought for a while that I made a testing error, I deleted the entry. After further testing, I verified that the error was indeed there.) 

Michal Kus

    import XCTest    
    import CoreLocation
    @testable import MoonKit

    final class MoonKitTestTests: XCTestCase {

    override func setUpWithError() throws {
        
    }

    override func tearDownWithError() throws {
        // Put teardown code here. This method is called after the invocation of each test method in the class.
    }

    func test1() throws {
        guard let timeZone = TimeZone(abbreviation: "PST") else {
            abort()
        }
        
        let location: CLLocation = .init(latitude: 37.317165398, longitude: -122.038499846)

        let moon = Moon.init(location: location, timeZone: 0)
        
        moon.setDate(MoonKit.createDateCurrentTimeZone(day: 13, month: 3, year: 2023, hour: 22, minute: 00, seconds: 00))
        moon.setTimeZone(timeZone.offset(moon.date))
        XCTAssertEqual(moon.timeZone, -7) //The value required to correctly calculate the moonrise and moonset.
        XCTAssertNotNil(moon.moonRise)
        if moon.moonRise != nil {
            XCTAssertEqual(moon.moonRise!.toString(), "03/13, 00:45") //OK
        }
        XCTAssertEqual(moon.moonSet!.toString(), "03/13, 10:37") //OK

        moon.setDate(MoonKit.createDateCurrentTimeZone(day: 12, month: 1, year: 2023, hour: 16, minute: 00, seconds: 00))
        moon.setTimeZone(timeZone.offset(moon.date))
        XCTAssertEqual(moon.timeZone, -9) //The value required to correctly calculate the moonrise and moonset.
        XCTAssertEqual(moon.moonRise!.toString(), "01/12, 21:42")
        XCTAssertEqual(moon.moonSet!.toString(), "01/12, 09:44")
        
        moon.setDate(MoonKit.createDateCurrentTimeZone(day: 26, month: 9, year: 2023, hour: 6, minute: 00, seconds: 00))
        moon.setTimeZone(timeZone.offset(moon.date))
        XCTAssertEqual(moon.timeZone, -7) //The value required to correctly calculate the moonrise and moonset.
        XCTAssertEqual(moon.moonRise!.toString(), "09/26, 17:52") //OK
        XCTAssertEqual(moon.moonSet!.toString(), "09/26, 03:26") //OK

        moon.setDate(MoonKit.createDateCurrentTimeZone(day: 26, month: 11, year: 2023, hour: 6, minute: 00, seconds: 00))
        moon.setTimeZone(timeZone.offset(moon.date))
        XCTAssertEqual(moon.timeZone, -8) //The value required to correctly calculate the moonrise and moonset.
        XCTAssertEqual(moon.moonRise!.toString(), "11/26, 16:19") //OK
        XCTAssertEqual(moon.moonSet!.toString(), "11/26, 06:18") //OK

    }

    func testPerformanceExample() throws {
        // This is an example of a performance test case.
        measure {
            // Put the code you want to measure the time of here.
        }
    }

    }

    extension Date {
    
    func toString() -> String {
        let df = DateFormatter()
        let custom = DateFormatter.dateFormat(fromTemplate: "MMdd HH:mm",
                                              options: 0,
                                              locale: Locale(identifier: "en"))
        df.dateFormat = custom
        return df.string(from: self)
    }
    

      }

      extension TimeZone {
    
    func offset(_ date: Date) -> Double {
        let res =
            Int(self.secondsFromGMT(for: date))
            + Int(self.daylightSavingTimeOffset(for: date))
            - Int(Calendar.current.timeZone.secondsFromGMT(for: date))
            - Int(Calendar.current.timeZone.daylightSavingTimeOffset(for: date))
        print("\(date.toString())  \(Int(self.secondsFromGMT(for: date)/3600)), \(Int(self.daylightSavingTimeOffset(for: date)/3600)), \(Int(Calendar.current.timeZone.secondsFromGMT(for: date)/3600)), \(Int(Calendar.current.timeZone.daylightSavingTimeOffset(for: date)/3600))")
        return Double(res)/3600.0
        
    }
    
    }

**Comment by davideilmito** [comment]
To proper calculate the time zone offset that you need to pass to the `setTimeZone(_ timeZone: Double)` method, I suggest to check `CLGeocoder` object in Swift [documentation](https://developer.apple.com/documentation/corelocation/clgeocoder), especially his `reverseGeocodeLocation` method.
From the completion handler of that method you will have a `CLPlacemark` from which you can retrieve the correct time zone for the given date and location. 


```swift

    func test1()  throws {
        
        let expectation = self.expectation(description: "myExpectation")
        
        let location: CLLocation = .init(latitude: 37.317165398, longitude: -122.038499846) //Cupertino Location
        
        let moon = Moon.init(location: location, timeZone: 0)
        
        moon.setDate(MoonKit.createDateCurrentTimeZone(day: 12, month: 1, year: 2023, hour: 16, minute: 00, seconds: 00))
        
        //Retrieving correct timezone by using CLGeocoder
        
        CLGeocoder().reverseGeocodeLocation(location) { (placemarks, err) in
            
            //Async call
            if let placemark = placemarks?.first{
                let newTimeZone = Double((placemark.timeZone?.secondsFromGMT(for: moon.date) ?? 0)) / 3600.0
                
                moon.setTimeZone(newTimeZone)
            }
            
            expectation.fulfill()
        }
        
        //Waiting Geocoder
        waitForExpectations(timeout: 5, handler: nil)
        
        print(moon.timeZone) //prints -8 which is correct
        XCTAssertEqual(moon.moonRise!.toString(), "01/12, 22:42")  //Mooncalc.org says that moonrise is at 22:44
        XCTAssertEqual(moon.moonSet!.toString(), "01/12, 10:44")    //Mooncalc.org says that moonset is at 10:45
        
    }

```

To compare the dates I suggest to do as I did inside ' UT_Moon' : 

`XCTAssertTrue(abs(expectedMoonRise.timeIntervalSince1970 - moonUnderTest.moonRise!.timeIntervalSince1970) <  UT_Moon.moonSetRiseThresholdInSeconds)` 

`UT_Moon.moonSetRiseThresholdInSeconds` has been set to 420 seconds, which are 7 minutes.

Please be aware that inside MoonKit the "better way to handle timezone" already discussed in SunKit [here](https://github.com/Sunlitt/SunKit/issues/9) has not been imported yet.

**Comment by BlackBird-One** [comment]
Thank you for your reply. 
I know where I went wrong: I was convinced I had to include my time zone. 
I'll gladly wait for the implementation of "better way to handle timezone", which I think will make everything easier.
